### ISSUE TITLE
Help offered

### ISSUE THREAD

**Issue by evhenious** [R0b0To/iGPlus#1]
Hello there! First of all, thank you for sharing the tool, it's a nice stuff. 

I am offering some volunteering help in optimizing the code, and maybe in adding a new stuff, or maybe polishing existing functionality. Do you mind if I create a branch here and play around a bit?

**Comment by R0b0To** [comment]
sure, I don't mind. There's definitely some optimizations to do in the code and I'm not motivated to do that.
